name: flutter_application_1
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  google_fonts: ^4.0.3
  geolocator: ^9.0.2
  geocoding: ^3.0.0
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
